### ISSUE TITLE
[FEATURE] Update Fedora to support .NET 6

### ISSUE THREAD

**Issue by nt-baker** [redhat-actions/openshift-actions-runners#16]
### Is your feature request related to a problem? Please describe.

My team would like to be able to extend the base image and install the .NET 6 SDK, but it is only supported on Fedora 34 and higher.

### Describe the solution you'd like

Update the base image to rely on Fedora 35 (unless there's some reason to go to 34 first).

### Describe alternatives you've considered

We can take the Containerfile for the base image and do this on our own, but this seems like others might benefit from the update as well.

Another option might be to have a .NET-specific base image if it was too disruptive to update Fedora for everyone.

### Additional context

I had already started down the road of making a PR for the changes, so I'll open that as well.

**Comment by divyansh42** [comment]
Released version `v2` of [openshift-actions-runner-chart](https://github.com/redhat-actions/openshift-actions-runner-chart) and [openshift-actions-runners](https://github.com/redhat-actions/openshift-actions-runners)
