### ISSUE TITLE
Document the   CLI and usage for runners

### ISSUE THREAD

**Issue by jduimovich** [redhat-actions/openshift-actions-runners#3]
Github Runner for OpenShift needs to document the environment, security aspects and built in CLI and usage for consumers customizing their runners.

**Comment by tetchel** [comment]
what do you mean by 'security aspects' ?

**Comment by tetchel** [comment]
https://github.com/redhat-actions/openshift-actions-runner/commit/231cf65ca0fb0df9e522b0696c60f83934d1ac4a
