### ISSUE TITLE
[FEATURE] Consider making $GITHUB_PAT optional if $RUNNER_TOKEN is supplied

### ISSUE THREAD

**Issue by willhaines** [redhat-actions/openshift-actions-runners#9]
### Is your feature request related to a problem? Please describe.

My GitHub account owns many repositories, and it would be safer to provide a token scoped to a single repo or organization, rather than a PAT with admin access to every repository/org. I'm referring to the token that is provided when going through these steps https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners.

### Describe the solution you'd like

Document the pros and cons of using a runner token vs a PAT, and document the process of using a runner token. Slightly modify `entrypoint.sh` to allow this without setting a bogus `$GITHUB_PAT`. It seems that removal of the runner would become a manual process in this case, per https://docs.github.com/en/actions/hosting-your-own-runners/removing-self-hosted-runners.

### Describe alternatives you've considered

Currently, I could supply a bogus `$GITHUB_PAT` along with a valid `$RUNNER_TOKEN`, and everything would work as desired, except for the `remove()` function that runs when the Pod is stopped.

### Additional context

I should have time to make a PR for this in the next week or two, unless someone pipes up that this is actually impossible, or that it would not be merged for some reason.

**Comment by tetchel** [comment]
Thank you for this detailed issue. I think this is a good idea and will accept this PR.

**Comment by tetchel** [comment]
this is now available in `v1.1.0` / `v1`
